### ISSUE TITLE
Your XML file is missing

### ISSUE THREAD

**Issue by ghost** [heades/blog#1]
Hey! I love your blog. I keep it on my PLT planet (https://brettgilio.com/planet.html) but your feed is no longer available at the URL https://blog.metatheorem.org/feed.xml

Is there somewhere else I could grab it?

**Comment by heades** [comment]
Thanks for the email.

I've switched my blog from jekyll to pandoc and I forgot to add it.  Should
be fixed now.

Best, Harley

**Comment by ghost** [comment]
Perfect! Thanks @heades
